imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

#monolog:
#    handlers:
#        main:
#            type:         fingers_crossed
#            action_level: error
#            handler:      nested
#        nested:
#            type:  stream
#            path:  "%kernel.logs_dir%/%kernel.environment%.log"
#            level: debug
#        console:
#            type:  console

monolog:
    handlers:
        mail:
            type: fingers_crossed
            action_level: critical
            handler: buffered
        buffered:
            type: buffer
            handler: swift
        swift:
            type: swift_mailer
            from_email: jobs@geolid.com
            to_email: g.lan-chow-wing@geolid.com
            subject: An Error Occurred on Jobs!
            level: debug
